/**
 * Centralized mock data for FlowSync Arena.
 *
 * Used in two places:
 * 1. API fallback in dashboard pages when the backend is unreachable
 * 2. Frontend component tests (imported directly)
 *
 * This prevents duplication between page-level fallback logic and tests.
 */
import type { ZoneStatus, QueueLive, Alert } from './types'

export const MOCK_ZONE_STATUS: ZoneStatus = {
  zones: [
    {
      id: 'entrance-north',
      name: 'North Entrance',
      capacity: 800,
      current_count: 620,
      density_level: 'amber',
      density_pct: 0.775,
      last_updated: new Date().toISOString(),
      adjacent_zones: ['main-hall', 'gate-a'],
      amenities: ['exit', 'info'],
      coordinates: { x: 40, y: 5, width: 20, height: 12 },
    },
    {
      id: 'main-hall',
      name: 'Main Hall',
      capacity: 3000,
      current_count: 1800,
      density_level: 'amber',
      density_pct: 0.6,
      last_updated: new Date().toISOString(),
      adjacent_zones: ['entrance-north', 'stage-area', 'east-wing', 'west-wing'],
      amenities: ['food', 'restroom', 'info'],
      coordinates: { x: 25, y: 25, width: 50, height: 35 },
    },
    {
      id: 'stage-area',
      name: 'Stage Area',
      capacity: 5000,
      current_count: 4200,
      density_level: 'red',
      density_pct: 0.84,
      last_updated: new Date().toISOString(),
      adjacent_zones: ['main-hall'],
      amenities: [],
      coordinates: { x: 30, y: 65, width: 40, height: 25 },
    },
    {
      id: 'east-wing',
      name: 'East Wing',
      capacity: 1200,
      current_count: 480,
      density_level: 'green',
      density_pct: 0.4,
      last_updated: new Date().toISOString(),
      adjacent_zones: ['main-hall', 'gate-b'],
      amenities: ['restroom', 'food'],
      coordinates: { x: 80, y: 25, width: 18, height: 35 },
    },
    {
      id: 'west-wing',
      name: 'West Wing',
      capacity: 1200,
      current_count: 290,
      density_level: 'empty',
      density_pct: 0.24,
      last_updated: new Date().toISOString(),
      adjacent_zones: ['main-hall', 'gate-c'],
      amenities: ['restroom', 'exit'],
      coordinates: { x: 2, y: 25, width: 18, height: 35 },
    },
    {
      id: 'gate-a',
      name: 'Gate A',
      capacity: 500,
      current_count: 390,
      density_level: 'amber',
      density_pct: 0.78,
      last_updated: new Date().toISOString(),
      adjacent_zones: ['entrance-north'],
      amenities: ['exit'],
      coordinates: { x: 35, y: 0, width: 10, height: 5 },
    },
    {
      id: 'gate-b',
      name: 'Gate B',
      capacity: 400,
      current_count: 120,
      density_level: 'green',
      density_pct: 0.3,
      last_updated: new Date().toISOString(),
      adjacent_zones: ['east-wing'],
      amenities: ['exit'],
      coordinates: { x: 90, y: 35, width: 8, height: 10 },
    },
    {
      id: 'gate-c',
      name: 'Gate C',
      capacity: 400,
      current_count: 85,
      density_level: 'empty',
      density_pct: 0.21,
      last_updated: new Date().toISOString(),
      adjacent_zones: ['west-wing'],
      amenities: ['exit'],
      coordinates: { x: 0, y: 35, width: 8, height: 10 },
    },
  ],
  avg_density: 0.55,
  calm_mode_active: false,
  timestamp: new Date().toISOString(),
}

export const MOCK_QUEUES: QueueLive = {
  queues: [
    {
      id: 'q1',
      zone_id: 'gate-a',
      zone_name: 'Gate A',
      name: 'Main Entry Queue',
      length: 47,
      avg_wait_min: 8.5,
      predicted_wait_min: 9,
      is_virtual: false,
      status: 'open',
      last_updated: new Date().toISOString(),
    },
    {
      id: 'q2',
      zone_id: 'gate-b',
      zone_name: 'Gate B',
      name: 'East Gate Queue',
      length: 12,
      avg_wait_min: 2.1,
      predicted_wait_min: 2.5,
      is_virtual: false,
      status: 'open',
      last_updated: new Date().toISOString(),
    },
    {
      id: 'q3',
      zone_id: 'main-hall',
      zone_name: 'Main Hall',
      name: 'Food Stall A Queue',
      length: 23,
      avg_wait_min: 5.0,
      predicted_wait_min: 6,
      is_virtual: true,
      status: 'open',
      last_updated: new Date().toISOString(),
    },
    {
      id: 'q4',
      zone_id: 'stage-area',
      zone_name: 'Stage Area',
      name: 'Premium Access',
      length: 8,
      avg_wait_min: 1.5,
      predicted_wait_min: 1.5,
      is_virtual: true,
      status: 'open',
      last_updated: new Date().toISOString(),
    },
  ],
  timestamp: new Date().toISOString(),
}

export const MOCK_ALERTS: Alert[] = [
  {
    id: 'a1',
    severity: 'warning',
    title: 'Congestion Alert',
    message: 'North Entrance is exceeding 75% capacity. Consider using Gate C.',
    zone_id: 'entrance-north',
    zone_name: 'North Entrance',
    created_at: new Date().toISOString(),
    resolved: false,
  },
]
